require_relative "../node_modules/react-native/scripts/react_native_pods"
require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"

platform :ios, "10.0"

target "AmpRN0633" do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target "AmpRN0633Tests" do
    inherit! :complete
    # Pods for testing
  end
end

target "AmpRN0633-tvOS" do
  # Pods for AmpRN0633-tvOS

  target "AmpRN0633-tvOSTests" do
    inherit! :search_paths
    # Pods for testing
  end
end
